name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    paths:
    - 'content-web/**'
    - '.github/workflows/fabrikam-web.yml'
    # Publish `v1.2.3` tags as releases.
    tags:
    - v*  
  # Run tests for any PRs.
  pull_request:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: fabrikam-web
  
jobs:
  build:
   runs-on: ubuntu-latest
   if: github.event_name == 'push'

   steps:
   - uses: actions/checkout@v2

   - name: Build image
     working-directory: content-web
     run: docker build . --file Dockerfile --tag $IMAGE_NAME

   - name: Log into GitHub Container Registry
     run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

   - name: Push image to GitHub Container Registry
     working-directory: content-web
     run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
        VERSION=${{ github.ref }}

        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION

        docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
